services:
  oracle-23ai:
    image: container-registry.oracle.com/database/free:23.4.0.0
    container_name: oracle-23ai
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=YourStrongPassword123
    volumes:
      - oracle_data_23ai:/opt/oracle/oradata
    restart: always

volumes:
  oracle_data_23ai: